---

- name: AddApacheUsers
  hosts: apache_servers
  vars:
      userlist: "{{ lookup('file', 'users.json') | from_json }}"
  vars_prompt:
      - name: admin_passwd
        prompt: "Enter admin password (no prefix)"
  tasks:
      - name: htpasswd
        become: yes
        no_log: yes
        loop: "{{ userlist }}"
        vars:
            ansible_become_password: "{{ passwd_pfx + admin_passwd }}"
        ansible.builtin.command:
                cmd: /usr/bin/htpasswd -i /etc/apache2/passwd {{ item.username }}
                stdin: "{{ passwd_pfx + item.password }}"

