---

- name: RootPasswords
  hosts: all
  vars_prompt:
      - name: admin_passwd
        prompt: "Enter admin password (no prefix)"
  tasks:
      - name: GeneratePassword
        set_fact:
                root_passwd: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
        delegate_to: localhost
      
      - debug:
                msg: "{{ inventory_hostname }} : {{ root_passwd }}"

      - name: ChangePassword
        become: yes
        ansible.builtin.user:
                name: root
                update_password: always
                password: "{{ root_passwd | password_hash('sha256') }}"
        vars:
                ansible_become_password: "{{ passwd_pfx + admin_passwd }}"

